# parts of this were adapted from https://github.com/higherkindness/droste/blob/bad7dae60a0c32e66918613068d6713d209cc6b4/.travis.yml
language: nix
sudo: required
dist: trusty

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork
  - name: publish-docs
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - env: TEST="docs"
      script: ./scripts/builds.sh docs
    - env: TEST="test JVM"
      script: ./scripts/builds.sh testJVM
    - env: TEST="test JS"
      script: ./scripts/builds.sh testJS
    - env: TEST="lint"
      script: ./scripts/builds.sh lint
    - env: TEST="coverage"
      script: ./scripts/builds.sh coverage
    - stage: release
      script: ./scripts/builds.sh release
    - stage: publish-docs
      # without this, docusaurus is getting errors looking at ~/.ssh/config
      install: mkdir -p ~/.ssh && touch ~/.ssh/config && chmod 600 ~/.ssh/config
      script: ./scripts/builds.sh publish-docs

before_install:
  - git fetch --tags

install: |
  if [ "$(ls -A $HOME/nix-cache)" ]; then
    sudo rm -rf /nix/*
    cp -a $HOME/nix-cache/* /nix
  fi

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier
    - $HOME/nix-cache

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local
  - |
    if [ ! "$(ls -A $HOME/nix-cache)" ]; then
      cp -a /nix/* $HOME/nix-cache
    fi
